/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalisadorLootRouteImport } from './routes/analisador-loot'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as DungeonsRouteImport } from './routes/dungeons'
import { Route as EstrategiaRouteImport } from './routes/estrategia'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as IniciantesRouteImport } from './routes/iniciantes'
import { Route as ItensRouteImport } from './routes/itens'
import { Route as LocalizacoesRouteImport } from './routes/localizacoes'
import { Route as MedalhasRouteImport } from './routes/medalhas'
import { Route as NpcsRouteImport } from './routes/npcs'
import { Route as OndeCacarRouteImport } from './routes/onde-cacar'
import { Route as PokedexRouteImport } from './routes/pokedex'
import { Route as SistemasRouteImport } from './routes/sistemas'
import { Route as StarRouteImport } from './routes/star'
import { Route as TalentosRouteImport } from './routes/talentos'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as TimesHoennRouteImport } from './routes/times-hoenn'
import { Route as DungeonSlugRouteImport } from './routes/dungeon.$slug'
import { Route as ItemSlugRouteImport } from './routes/item.$slug'
import { Route as PokemonSlugRouteImport } from './routes/pokemon.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisadorLootRoute = AnalisadorLootRouteImport.update({
  id: '/analisador-loot',
  path: '/analisador-loot',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonsRoute = DungeonsRouteImport.update({
  id: '/dungeons',
  path: '/dungeons',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiaRoute = EstrategiaRouteImport.update({
  id: '/estrategia',
  path: '/estrategia',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciantesRoute = IniciantesRouteImport.update({
  id: '/iniciantes',
  path: '/iniciantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensRoute = ItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacoesRoute = LocalizacoesRouteImport.update({
  id: '/localizacoes',
  path: '/localizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MedalhasRoute = MedalhasRouteImport.update({
  id: '/medalhas',
  path: '/medalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsRoute = NpcsRouteImport.update({
  id: '/npcs',
  path: '/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeCacarRoute = OndeCacarRouteImport.update({
  id: '/onde-cacar',
  path: '/onde-cacar',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexRoute = PokedexRouteImport.update({
  id: '/pokedex',
  path: '/pokedex',
  getParentRoute: () => rootRouteImport,
} as any)
const SistemasRoute = SistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const StarRoute = StarRouteImport.update({
  id: '/star',
  path: '/star',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentosRoute = TalentosRouteImport.update({
  id: '/talentos',
  path: '/talentos',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesHoennRoute = TimesHoennRouteImport.update({
  id: '/times-hoenn',
  path: '/times-hoenn',
  getParentRoute: () => rootRouteImport,
} as any)
const DungeonSlugRoute = DungeonSlugRouteImport.update({
  id: '/dungeon/$slug',
  path: '/dungeon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemSlugRoute = ItemSlugRouteImport.update({
  id: '/item/$slug',
  path: '/item/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonSlugRoute = PokemonSlugRouteImport.update({
  id: '/pokemon/$slug',
  path: '/pokemon/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analisador-loot': typeof AnalisadorLootRoute
  '/assistente': typeof AssistenteRoute
  '/boost': typeof BoostRoute
  '/drops': typeof DropsRoute
  '/dungeons': typeof DungeonsRoute
  '/estrategia': typeof EstrategiaRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/iniciantes': typeof IniciantesRoute
  '/itens': typeof ItensRoute
  '/localizacoes': typeof LocalizacoesRoute
  '/medalhas': typeof MedalhasRoute
  '/npcs': typeof NpcsRoute
  '/onde-cacar': typeof OndeCacarRoute
  '/pokedex': typeof PokedexRoute
  '/sistemas': typeof SistemasRoute
  '/star': typeof StarRoute
  '/talentos': typeof TalentosRoute
  '/tasks': typeof TasksRoute
  '/tier-list': typeof TierListRoute
  '/times-hoenn': typeof TimesHoennRoute
  '/dungeon/$slug': typeof DungeonSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analisador-loot': typeof AnalisadorLootRoute
  '/assistente': typeof AssistenteRoute
  '/boost': typeof BoostRoute
  '/drops': typeof DropsRoute
  '/dungeons': typeof DungeonsRoute
  '/estrategia': typeof EstrategiaRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/iniciantes': typeof IniciantesRoute
  '/itens': typeof ItensRoute
  '/localizacoes': typeof LocalizacoesRoute
  '/medalhas': typeof MedalhasRoute
  '/npcs': typeof NpcsRoute
  '/onde-cacar': typeof OndeCacarRoute
  '/pokedex': typeof PokedexRoute
  '/sistemas': typeof SistemasRoute
  '/star': typeof StarRoute
  '/talentos': typeof TalentosRoute
  '/tasks': typeof TasksRoute
  '/tier-list': typeof TierListRoute
  '/times-hoenn': typeof TimesHoennRoute
  '/dungeon/$slug': typeof DungeonSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analisador-loot': typeof AnalisadorLootRoute
  '/assistente': typeof AssistenteRoute
  '/boost': typeof BoostRoute
  '/drops': typeof DropsRoute
  '/dungeons': typeof DungeonsRoute
  '/estrategia': typeof EstrategiaRoute
  '/favoritos': typeof FavoritosRoute
  '/guias': typeof GuiasRoute
  '/iniciantes': typeof IniciantesRoute
  '/itens': typeof ItensRoute
  '/localizacoes': typeof LocalizacoesRoute
  '/medalhas': typeof MedalhasRoute
  '/npcs': typeof NpcsRoute
  '/onde-cacar': typeof OndeCacarRoute
  '/pokedex': typeof PokedexRoute
  '/sistemas': typeof SistemasRoute
  '/star': typeof StarRoute
  '/talentos': typeof TalentosRoute
  '/tasks': typeof TasksRoute
  '/tier-list': typeof TierListRoute
  '/times-hoenn': typeof TimesHoennRoute
  '/dungeon/$slug': typeof DungeonSlugRoute
  '/item/$slug': typeof ItemSlugRoute
  '/pokemon/$slug': typeof PokemonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analisador-loot'
    | '/assistente'
    | '/boost'
    | '/drops'
    | '/dungeons'
    | '/estrategia'
    | '/favoritos'
    | '/guias'
    | '/iniciantes'
    | '/itens'
    | '/localizacoes'
    | '/medalhas'
    | '/npcs'
    | '/onde-cacar'
    | '/pokedex'
    | '/sistemas'
    | '/star'
    | '/talentos'
    | '/tasks'
    | '/tier-list'
    | '/times-hoenn'
    | '/dungeon/$slug'
    | '/item/$slug'
    | '/pokemon/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analisador-loot'
    | '/assistente'
    | '/boost'
    | '/drops'
    | '/dungeons'
    | '/estrategia'
    | '/favoritos'
    | '/guias'
    | '/iniciantes'
    | '/itens'
    | '/localizacoes'
    | '/medalhas'
    | '/npcs'
    | '/onde-cacar'
    | '/pokedex'
    | '/sistemas'
    | '/star'
    | '/talentos'
    | '/tasks'
    | '/tier-list'
    | '/times-hoenn'
    | '/dungeon/$slug'
    | '/item/$slug'
    | '/pokemon/$slug'
  id:
    | '__root__'
    | '/'
    | '/analisador-loot'
    | '/assistente'
    | '/boost'
    | '/drops'
    | '/dungeons'
    | '/estrategia'
    | '/favoritos'
    | '/guias'
    | '/iniciantes'
    | '/itens'
    | '/localizacoes'
    | '/medalhas'
    | '/npcs'
    | '/onde-cacar'
    | '/pokedex'
    | '/sistemas'
    | '/star'
    | '/talentos'
    | '/tasks'
    | '/tier-list'
    | '/times-hoenn'
    | '/dungeon/$slug'
    | '/item/$slug'
    | '/pokemon/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalisadorLootRoute: typeof AnalisadorLootRoute
  AssistenteRoute: typeof AssistenteRoute
  BoostRoute: typeof BoostRoute
  DropsRoute: typeof DropsRoute
  DungeonsRoute: typeof DungeonsRoute
  EstrategiaRoute: typeof EstrategiaRoute
  FavoritosRoute: typeof FavoritosRoute
  GuiasRoute: typeof GuiasRoute
  IniciantesRoute: typeof IniciantesRoute
  ItensRoute: typeof ItensRoute
  LocalizacoesRoute: typeof LocalizacoesRoute
  MedalhasRoute: typeof MedalhasRoute
  NpcsRoute: typeof NpcsRoute
  OndeCacarRoute: typeof OndeCacarRoute
  PokedexRoute: typeof PokedexRoute
  SistemasRoute: typeof SistemasRoute
  StarRoute: typeof StarRoute
  TalentosRoute: typeof TalentosRoute
  TasksRoute: typeof TasksRoute
  TierListRoute: typeof TierListRoute
  TimesHoennRoute: typeof TimesHoennRoute
  DungeonSlugRoute: typeof DungeonSlugRoute
  ItemSlugRoute: typeof ItemSlugRoute
  PokemonSlugRoute: typeof PokemonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisador-loot': {
      id: '/analisador-loot'
      path: '/analisador-loot'
      fullPath: '/analisador-loot'
      preLoaderRoute: typeof AnalisadorLootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeons': {
      id: '/dungeons'
      path: '/dungeons'
      fullPath: '/dungeons'
      preLoaderRoute: typeof DungeonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategia': {
      id: '/estrategia'
      path: '/estrategia'
      fullPath: '/estrategia'
      preLoaderRoute: typeof EstrategiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciantes': {
      id: '/iniciantes'
      path: '/iniciantes'
      fullPath: '/iniciantes'
      preLoaderRoute: typeof IniciantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens': {
      id: '/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof ItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacoes': {
      id: '/localizacoes'
      path: '/localizacoes'
      fullPath: '/localizacoes'
      preLoaderRoute: typeof LocalizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medalhas': {
      id: '/medalhas'
      path: '/medalhas'
      fullPath: '/medalhas'
      preLoaderRoute: typeof MedalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs': {
      id: '/npcs'
      path: '/npcs'
      fullPath: '/npcs'
      preLoaderRoute: typeof NpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-cacar': {
      id: '/onde-cacar'
      path: '/onde-cacar'
      fullPath: '/onde-cacar'
      preLoaderRoute: typeof OndeCacarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex': {
      id: '/pokedex'
      path: '/pokedex'
      fullPath: '/pokedex'
      preLoaderRoute: typeof PokedexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sistemas': {
      id: '/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof SistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/star': {
      id: '/star'
      path: '/star'
      fullPath: '/star'
      preLoaderRoute: typeof StarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talentos': {
      id: '/talentos'
      path: '/talentos'
      fullPath: '/talentos'
      preLoaderRoute: typeof TalentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times-hoenn': {
      id: '/times-hoenn'
      path: '/times-hoenn'
      fullPath: '/times-hoenn'
      preLoaderRoute: typeof TimesHoennRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dungeon/$slug': {
      id: '/dungeon/$slug'
      path: '/dungeon/$slug'
      fullPath: '/dungeon/$slug'
      preLoaderRoute: typeof DungeonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$slug': {
      id: '/item/$slug'
      path: '/item/$slug'
      fullPath: '/item/$slug'
      preLoaderRoute: typeof ItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$slug': {
      id: '/pokemon/$slug'
      path: '/pokemon/$slug'
      fullPath: '/pokemon/$slug'
      preLoaderRoute: typeof PokemonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalisadorLootRoute: AnalisadorLootRoute,
  AssistenteRoute: AssistenteRoute,
  BoostRoute: BoostRoute,
  DropsRoute: DropsRoute,
  DungeonsRoute: DungeonsRoute,
  EstrategiaRoute: EstrategiaRoute,
  FavoritosRoute: FavoritosRoute,
  GuiasRoute: GuiasRoute,
  IniciantesRoute: IniciantesRoute,
  ItensRoute: ItensRoute,
  LocalizacoesRoute: LocalizacoesRoute,
  MedalhasRoute: MedalhasRoute,
  NpcsRoute: NpcsRoute,
  OndeCacarRoute: OndeCacarRoute,
  PokedexRoute: PokedexRoute,
  SistemasRoute: SistemasRoute,
  StarRoute: StarRoute,
  TalentosRoute: TalentosRoute,
  TasksRoute: TasksRoute,
  TierListRoute: TierListRoute,
  TimesHoennRoute: TimesHoennRoute,
  DungeonSlugRoute: DungeonSlugRoute,
  ItemSlugRoute: ItemSlugRoute,
  PokemonSlugRoute: PokemonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>
  }
}
